GET http://localhost:8000/comments

GET http://localhost:8000/comments?postId=1234

POST  http://localhost:8000/comments
Content-Type: application/json

{
    "message": "Nice post!",
    "sender": "Guy123",
    "postId": "1234"
}