###  get all comments
GET http://localhost:8000/comments

###  get comments by postId
GET http://localhost:8000/comments?postId=1234

### create a new comment
PUT http://localhost:8000/comments/5678
Content-Type: application/json

{
  "message": "Updated message"
} 
