GET http://localhost:8000/posts

GET http://localhost:8000/posts/1234

GET http://localhost:8000/posts?sender=1234

POST http://localhost:8000/posts
Content-Type: application/json

{
    "message": "hi! what's up?",
    "sender": "1234"
}

PUT http://localhost:8000/posts/1234
Content-Type: application/json

{
    "sender": "Mayan",
    "message": "updated message content",
    "_id": "1234"
}